declare const LANGS: string[];
declare const getLang: (runtime: any) => string;
declare const RUNTIMES: {
    "Python2.7": string;
    "Python3.6": string;
    "Go1.8": string;
    Java8: string;
    "Node.js6.10": string;
    "Node.js8.10": string;
    "Node.js10.16": string;
    "Node.js12.13": string;
    "C#(.NET Core 2.0)": string;
    "C#(.NET Core 2.1)": string;
    "C#(.NET Core 3.1)": string;
    Custom: string;
    "PHP7.3": string;
};
declare const CONFIGS: {
    compName: string;
    compFullname: string;
    functionName: string;
    handler: string;
    codeUri: string;
    timeout: number;
    memorySize: number;
    runtime(runtime: string, logger: any): any;
    description(app?: string): string;
    codeType: string;
    pkg: string;
    dashBoardUrl: string;
    endpoints: {
        "af-south-1": string;
        "cn-north-4": string;
        "cn-north-1": string;
        "cn-east-2": string;
        "cn-east-3": string;
        "cn-south-1": string;
        "na-mexico-1": string;
        "sa-brazil-1": string;
        "la-south-2": string;
        "ap-southeast-2": string;
        "ap-southeast-1": string;
        "ap-southeast-3": string;
    };
};
